### ISSUE TITLE
NSIS URL unable to load

### ISSUE THREAD

**Issue by tyhallcsu** [doadin/DelugeBuildFromSource#4]
```
    if ( -not (Test-Path 'C:\DelugeDownloads\nsis-3.08.zip' -PathType Leaf) ) { 
        Write-Host "Downloading NSIS..."
        $WebClient.DownloadFile("https://downloads.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08.zip","C:\DelugeDownloads\nsis-3.08.zip")
    }
```

I cannot get the URL for NSIS to download:
https://phoenixnap.dl.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08.zip

Rather, you may want to use this URL:
https://downloads.sourceforge.net/project/nsis/NSIS%203/3.08/nsis-3.08.zip

Unless there is a particular reason you decided to use "phoenixnap"?

**Comment by doadin** [comment]
updated the url. its just the mirror I got when I lasted downloaded, idk why that mirror is not working now.

**Comment by doadin** [comment]
The script needs a direct url not a webpage that redirects,so no download.sourceforge would not work.
